---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Upgrade pip
  - pip install --upgrade pip
  - pip install ansible-container[docker]

script:
  # Run build
  - ansible-container build
